apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - edgeamqbrokers/
  - orionldcontextbrokers/
  - scorpiobrokers/
  - iotagentjsons/
  - smartabyarsmartvillages/
  - trafficsimulations/
  - trafficflowobserveds/
