apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - operators/
  - edgemongodbs/
  - edgepostgress/
  - edgeamqbrokers/
  - orionldcontextbrokers/
  - iotagentjsons/
  - smartabyarsmartvillages/

