apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://solr.apache.org/operator/downloads/crds/v0.7.1/all-with-dependencies.yaml
  - roles
  - rolebindings
  - securitycontextconstraints
