---
# tasks file for TrafficFlowObserved

- name: "Query the IOT Agent service"
  set_fact:
    iotagent_port: "{{ query('kubernetes.core.k8s', kind='Service', resource_name=values.iotagent.name, namespace=values.iotagent.namespace)[0].spec.ports | community.general.json_query(QUERY) | first }}"
  vars: 
    QUERY: |-
      [?name=='north'].port
  when: values.iotagent.base_url == ''
- name: "Configure iotagent_base_url"
  set_fact:
    iotagent_route: "{{ query('kubernetes.core.k8s', kind='Route', resource_name=values.iotagent.name, namespace=values.iotagent.namespace)[0].spec.host | default('') }}"
  when: values.iotagent.base_url == ''
- name: "Configure iotagent_base_url"
  set_fact:
    iotagent_base_url: "http://{{ iotagent_route | default( values.iotagent.name + '.' + values.iotagent.namespace + '.svc', true ) }}:{{ iotagent_port }}"
  when: values.iotagent.base_url == ''
- name: "Configure iotagent base url"
  set_fact:
    iotagent_base_url: "{{ values.iotagent.base_url }}"
  when: values.iotagent.base_url != ''
- name: "Update values.iotagent.base_url"
  set_fact:
    values: "{{ values | combine({'iotagent':{'base_url':iotagent_base_url}}, recursive=true) }}"
  when: values.iotagent.base_url == ''

- name: "Query the Orion-LD Context Broker service"
  set_fact:
    context_broker_port: "{{ query('kubernetes.core.k8s', kind='Service', resource_name=values.context_broker.name, namespace=values.context_broker.namespace)[0].spec.ports | community.general.json_query(QUERY) | first }}"
  vars: 
    QUERY: |-
      [?name=='http'].port
  when: values.context_broker.base_url == ''
- name: "Configure context_broker_base_url"
  set_fact:
    context_broker_route: "{{ query('kubernetes.core.k8s', kind='Route', resource_name=values.context_broker.name, namespace=values.context_broker.namespace)[0].spec.host | default('') }}"
  when: values.context_broker.base_url == ''
- name: "Configure context_broker_base_url"
  set_fact:
    context_broker_base_url: "http://{{ context_broker_route | default( values.context_broker.name + '.' + values.context_broker.namespace + '.svc', true ) }}:{{ context_broker_port }}"
  when: values.context_broker.base_url == ''
- name: "Configure context broker base url"
  set_fact:
    context_broker_base_url: "{{ values.context_broker.base_url }}"
  when: values.context_broker.base_url != ''
- name: "Update values.context_broker.base_url"
  set_fact:
    values: "{{ values | combine({'context_broker':{'base_url':context_broker_base_url}}, recursive=true) }}"
  when: values.context_broker.base_url == ''

- name: Run Ansible role iotagent-json-service-group
  include_role:
    name: iotagent-json-service-group
- name: Run Ansible role iotagent-json-device
  include_role:
    name: iotagent-json-device
- name: Run Ansible role iotagent-json-subscription
  include_role:
    name: iotagent-json-subscription
- name: Run Ansible role iotagent-json-send
  include_role:
    name: iotagent-json-send
    